# Generated by Django 3.2 on 2021-04-15 19:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_auto_20210320_1627'),
        ('stockinf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('orderno', models.CharField(max_length=255, verbose_name='委託單號')),
                ('stockno', models.CharField(max_length=255, verbose_name='股票代號')),
                ('amount', models.IntegerField(verbose_name='成交數量')),
                ('orderType', models.CharField(max_length=24, verbose_name='成交種類')),
                ('price', models.FloatField(verbose_name='成交價')),
                ('state', models.CharField(max_length=255, verbose_name='委託單狀態')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='委託時間')),
                ('tradeCategory', models.CharField(default='null', max_length=255, verbose_name='交易種類')),
                ('tradeType', models.CharField(default='null', max_length=255, verbose_name='交易類別')),
                ('takeprice', models.CharField(default='null', max_length=255, verbose_name='取價類別')),
                ('pendingType', models.CharField(default='null', max_length=128, verbose_name='掛單類別')),
                ('stockinf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockinf.stockinf')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'stockorder',
            },
        ),
    ]
