# Generated by Django 3.1.2 on 2021-03-08 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stockinf', '__first__'),
        ('users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('orderno', models.CharField(max_length=255, verbose_name='委託單號')),
                ('stockno', models.CharField(max_length=255, verbose_name='股票代號')),
                ('amount', models.IntegerField(verbose_name='成交數量')),
                ('orderType', models.CharField(max_length=24, verbose_name='成交種類')),
                ('price', models.IntegerField(verbose_name='成交價')),
                ('state', models.CharField(max_length=255, verbose_name='委託單狀態')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='委託時間')),
                ('stockinf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockinf.stockinf')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'stockorder',
            },
        ),
    ]
