# Generated by Django 3.1.2 on 2021-03-20 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_auto_20210320_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField(verbose_name='庫存數量')),
                ('price', models.IntegerField(verbose_name='成交價格')),
                ('stockno', models.CharField(max_length=255, verbose_name='股票代號')),
                ('tradeType', models.CharField(max_length=255, verbose_name='交易類別')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'inventory',
            },
        ),
    ]
