# Generated by Django 3.1.2 on 2021-03-08 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stockinf',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stockid', models.CharField(max_length=24, verbose_name='股票代號')),
                ('stockname', models.CharField(max_length=24, verbose_name='股票名稱')),
                ('companyInf', models.TextField(verbose_name='公司簡介')),
                ('logo', models.ImageField(upload_to='stocklogo/')),
            ],
            options={
                'db_table': 'stockinf',
            },
        ),
    ]
