# Generated by Django 3.1.2 on 2021-03-20 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.IntegerField(verbose_name='用戶餘額'),
        ),
    ]
