# Generated by Django 3.1.2 on 2021-03-08 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stockid', models.CharField(max_length=24, verbose_name='股票代號')),
                ('stockname', models.CharField(max_length=24, verbose_name='股票名稱')),
                ('date', models.DateTimeField(auto_now=True)),
                ('openprice', models.FloatField(verbose_name='開盤價')),
                ('highprice', models.FloatField(verbose_name='最高價')),
                ('lowprice', models.FloatField(verbose_name='最低價')),
                ('closeprice', models.FloatField(verbose_name='收盤價')),
                ('adj_close', models.FloatField(verbose_name='調整收盤價')),
                ('volume', models.IntegerField(verbose_name='成交量')),
            ],
            options={
                'db_table': 'stock',
            },
        ),
    ]
